apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobol-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cobol-app
  template:
    metadata:
      labels:
        app: cobol-app
    spec:
      containers:
      - name: cobol-app
        image: aryobama/cobol-app:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cobol-app-service
spec:
  type: LoadBalancer
  selector:
    app: cobol-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000